const okinawa = require('./okinawa');
const tochigi = require('./tochigi');
const gunma = require('./gunma');
const toyama = require('./toyama');
const fukui = require('./fukui');
const yamanashi = require('./yamanashi');
const mie = require('./mie');
const shiga = require('./shiga');
const kyoto = require('./kyoto');
const ibaraki = require('./ibaraki');
const osaka = require('./osaka');

okinawa.transform();
tochigi.transform();
gunma.transform();
toyama.transform();
fukui.transform();
yamanashi.transform();
mie.transform();
shiga.transform();
kyoto.transform();
ibaraki.transform();
osaka.transform();